// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlEDGnCl9Lzkwio5uooHDiMGq8YHWqmAA',
    appId: '1:1083503274897:web:92ba53ca4ed1326044c830',
    messagingSenderId: '1083503274897',
    projectId: 'padala-raghavendra-reddy',
    authDomain: 'padala-raghavendra-reddy.firebaseapp.com',
    storageBucket: 'padala-raghavendra-reddy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDZusnxlYIz1cASlWSuNg4nsyakpLuafs',
    appId: '1:1083503274897:android:236f23c4a8a4c9da44c830',
    messagingSenderId: '1083503274897',
    projectId: 'padala-raghavendra-reddy',
    storageBucket: 'padala-raghavendra-reddy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGBelzMLMq6XRgex57Q7stFWF1ZkJRyUY',
    appId: '1:1083503274897:ios:b3930a106f6438b144c830',
    messagingSenderId: '1083503274897',
    projectId: 'padala-raghavendra-reddy',
    storageBucket: 'padala-raghavendra-reddy.firebasestorage.app',
    iosBundleId: 'com.example.raghavareddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGBelzMLMq6XRgex57Q7stFWF1ZkJRyUY',
    appId: '1:1083503274897:ios:b3930a106f6438b144c830',
    messagingSenderId: '1083503274897',
    projectId: 'padala-raghavendra-reddy',
    storageBucket: 'padala-raghavendra-reddy.firebasestorage.app',
    iosBundleId: 'com.example.raghavareddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlEDGnCl9Lzkwio5uooHDiMGq8YHWqmAA',
    appId: '1:1083503274897:web:1032314d0aebe50844c830',
    messagingSenderId: '1083503274897',
    projectId: 'padala-raghavendra-reddy',
    authDomain: 'padala-raghavendra-reddy.firebaseapp.com',
    storageBucket: 'padala-raghavendra-reddy.firebasestorage.app',
  );
}
