Map<String, String> techStackImages = {
  'Python': 'assets/icons/python.svg',
  'c':'assets/icons/icons8-c-programming-100.png',
  'java':'assets/icons/icons8-java-94.png',
  'Flutter': 'assets/icons/flutter.svg',
  'Dart': 'assets/icons/icons8-dart-48.png',
  'Firebase': 'assets/icons/firebase.svg',
  'MongoDB': 'assets/icons/mongo.svg',
  'express': 'assets/icons/express-js.png',
  'NodeJS': 'assets/icons/node.svg',
  // 'Docker': 'assets/icons/docker.svg',
  'Typescript': 'assets/icons/ts.svg',
  'Linux': 'assets/icons/linux.png',
  'Git': 'assets/icons/git.png',
  // 'Go': 'assets/icons/go.png',
  // 'Kubernetes': 'assets/icons/k8.svg',
  'AWS': 'assets/icons/aws.svg',
  // 'Tensorflow': 'assets/icons/tf.svg',
};
